name: movie_app_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  retrofit: ">=4.0.0 <5.0.0"
  dio: ^5.3.3
  logger: ^2.0.2+1
  get_it: ^7.6.4
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  intl: ^0.18.1
  flutter_localization: ^0.1.14
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  retrofit_generator: ">=5.0.0 <6.0.0"
  build_runner: ">=2.3.0 <4.0.0"
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic

flutter_intl:
  enabled: true
